### PR TITLE
feat: Add MIDI constants

### PR DESCRIPTION
**Pull request by MarquisdeGeek**
Using numbers like 144 for note on, or 38 to switch to a bass guitar, is a little opaque for my tastes so I've added all the names from the General MIDI spec to self-document my generative music.

### CODE REVIEW

**Comment by Julusian** [comment]
I'm open to merging this, but I think the exports of the values need better names.

Perhaps this could exported from `midi.js` as:
```
Constants: {
  Instruments,
  Drums,
  Notes,
  Messages,
}
```

**Comment by MarquisdeGeek** [comment]
The instrument and drum lists are only valid for GM (General MIDI) instruments, so would need a designation. Would suggest GMDrums, instead of GeneralMIDIDrums to avoid making the names too long?

**Comment by Julusian** [comment]
I feel like 'GM' doesn't convey enough meaning to explain anything.
Perhaps this would be better added as a comment on the export/documentation, that should be visible to users when looking to use the values

**Comment by MarquisdeGeek** [comment]
Bump for the above changes, as suggested.

**Pull request merged**
