### PR TITLE
Update RtMidi to latest

### PR DESCRIPTION
**Pull request by beaugunderson**
I tested this locally on an M2 MBP running 14.1.2 and everything worked as expected.

### CODE REVIEW

**Comment by beaugunderson** [comment]
ah you probably don’t want the yarn upgrade portion of this! sorry, didn’t
realize I had pushed that… if you revert those last two commits and just
keep the rtmidi one you should be good

**Comment by beaugunderson** [comment]
(i found that using yarn v4 in a project that pulls in this module results
in this module not working on older macos or at all on windows… so i went
back to yarn v1 in that project since i could never figure out why. but the
new rtmidi works flawlessly)

**Comment by Julusian** [comment]
> i think it’s also going to prevent people using this module from being
able to use it on yarn 1 since they’ll get a corepack error

I am pretty certain that is not the case. I have some other libraries where they are using yarn 4 in applications using yarn 1 (and some the other way around too).
The only time I am aware it will matter, is it makes doing a `yarn link` harder, but not impossible. It may result in setting up the link manually

**Comment by beaugunderson** [comment]
unfortunately it does break yarn v1, I just upgraded to 3.2.0 and verified:

```
[write] 9:34:53 AM dist-electron/electron-env.d.js
[write] 9:34:53 AM dist-electron/main/index.js
[write] 9:34:53 AM dist-electron/main/midi-manager.js
[write] 9:34:53 AM dist-electron/preload/index.js
  • electron-builder  version=24.9.1 os=23.2.0
  • loaded configuration  file=/Users/beau/p/m-editor/electron-builder.json5
  • writing effective config  file=release/0.0.70/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@julusian/midi@3.2.0 platform=darwin arch=x64
  • rebuilding native dependency  name=@julusian/midi version=3.2.0
  ⨯ cannot execute  cause=exit status 1
error This project's package.json defines "packageManager": "yarn@4.0.2". However the current global version of Yarn is 1.22.21.

    Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
    Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.

                    command=/Users/beau/.nvm/versions/node/v21.5.0/bin/node /Users/beau/.nvm/versions/node/v21.5.0/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/Users/beau/p/m-editor/node_modules/@julusian/midi
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by beaugunderson** [comment]
never mind, after some reading it seems that all I needed was `corepack enable`; that seems to have taken care of the build error without changing any of the yarn versions, global or otherwise... sorry for the noise :)

will let you know if it affects where the module runs though

**Comment by Julusian** [comment]
> unfortunately it does break yarn v1, I just upgraded to 3.2.0 and verified:

oh, I didn't think of that.. thats a bug in electron-builder though
it is trying to recompile this library, but there is no reason for it to do that in almost all circumstances. unfortunately it does this because it was written to handle libraries which did need to be recompiled for electron, and there isn't a way to opt out of it doing that

**Comment by beaugunderson** [comment]
alright false alarm--the rebuilt version using electron-builder on yarn v1 does still work on Windows. I am confident that if I upgraded my local project to yarn v4 again the rebuilt version would break on Windows, but I don't think that's the fault of this package (since it did the same thing when this package was using yarn v1). thanks for the merge! 🙏

**Comment by aunnop739** [comment]
@

**Pull request merged**
